const RULE_ERROR_MESSAGES: Readonly<Record<string, string>> = {
  ABILITY_EFFECT_REQUIRED: '技能缺少可结算的效果。',
  ABILITY_ID_REQUIRED: '技能数据不完整。',
  ABILITY_TEXT_REQUIRED: '技能说明不完整。',
  AI_INVALID_PLAN: '演武对手未能完成合法行动。',
  AI_LOCK_FAILED: '演武对手未能锁定行动。',
  ALREADY_JOINED: '你已经加入当前房间。',
  AUTHENTICATION_FAILED: '服务器密码不正确。',
  AUTHENTICATION_REQUIRED: '该服务器需要密码。',
  BANNER_ALREADY_USED: '本局已经举过旗。',
  CARD_ID_REQUIRED: '卡牌数据不完整。',
  CARD_NOT_IN_HAND: '该卡牌已不在你的手牌中。',
  CATALOG_VERSION_MISMATCH: '服务器与客户端的内容版本不一致，请更新后重试。',
  DECK_CARD_LIST_MISMATCH: '提交的牌组内容不一致，请重新选择牌组。',
  DECK_PAYLOAD_REQUIRED: '服务器没有收到完整的牌组数据。',
  DECK_REQUIRED: '请先选择一套合法牌组。',
  DECK_SCHEMA_MISMATCH: '该牌组来自不兼容的版本。',
  DUPLICATE_CARD: '牌组中不能加入重复卡牌。',
  DUPLICATE_CARD_ABILITY: '卡牌包含重复技能。',
  DUPLICATE_CARD_ID: '卡牌目录中存在重复卡牌。',
  DUPLICATE_DEPLOYMENT: '同一张手牌每回合只能部署一次。',
  DUPLICATE_OR_EMPTY_SLUG: '卡牌目录数据不完整。',
  DUPLICATE_PLAYER_ID: '玩家身份发生冲突，请重新连接。',
  EMPTY_MESSAGE: '服务器没有收到有效操作。',
  EVENT_LIMIT_EXCEEDED: '本次技能连锁过长，结算已停止。',
  FRONT_CAPACITY: '该战线没有足够容量。',
  FRONT_DEPLOYMENT_LIMIT: '该战线本回合不能再部署卡牌。',
  FRONT_NOT_FOUND: '目标战线不存在。',
  GAME_ACTIVE: '当前战局仍在进行中。',
  GAME_ENDED: '当前战局已经结束。',
  GAME_NOT_ACTIVE: '当前没有正在进行的战局。',
  GAME_NOT_ENDED: '战局结束后才能执行此操作。',
  HIGH_COST_BLOCKED: '该战线禁止部署高费卡牌。',
  INCOMPATIBLE_FRONT_POOL: '本局战线组合存在冲突，请重新开始。',
  INSUFFICIENT_ENERGY: '军令不足，无法提交当前计划。',
  INSUFFICIENT_FRONTS: '可用战线数量不足。',
  INVALID_BALANCE_PROFILE: '卡牌数值数据不完整。',
  INVALID_CARD_DATA: '卡牌目录无法载入。',
  INVALID_CONDITION: '技能条件无法识别。',
  INVALID_COST: '卡牌费用数据无效。',
  INVALID_DECK: '所选牌组不合法。',
  INVALID_DECK_ID: '牌组标识无效。',
  INVALID_DECK_NAME: '牌组名称不符合要求。',
  INVALID_DECK_SIZE: '牌组必须包含十二张不同卡牌。',
  INVALID_EFFECT: '技能效果无法识别。',
  INVALID_EFFECT_SELECTOR: '技能效果目标无法识别。',
  INVALID_FRONT_DATA: '战线数据无法载入。',
  INVALID_MESSAGE: '服务器无法识别本次操作。',
  INVALID_MOVE_SOURCE: '无法调遣这张卡牌。',
  INVALID_MOVE_TARGET: '调遣目标战线无效。',
  INVALID_PLAYER_COUNT: '战局需要两名玩家。',
  INVALID_POWER: '卡牌战力数据无效。',
  INVALID_REQUEST: '服务器无法完成本次操作。',
  INVALID_SELECTOR: '技能目标无法识别。',
  INVALID_SERIALIZED_GAME: '对局记录已损坏或版本不兼容。',
  INVALID_TRIGGER: '技能触发时机无法识别。',
  JOIN_REQUIRED: '请先加入房间。',
  LOW_COST_BLOCKED: '该战线禁止部署低费卡牌。',
  MOVEMENT_BLOCKED: '战线规则禁止本次调遣。',
  NAME_IN_USE: '该玩家名已被使用。',
  NAME_REQUIRED: '请输入玩家名。',
  NOT_IN_GAME: '你尚未进入战局。',
  NOT_PLANNING: '当前不能修改行动计划。',
  OPPONENT_NOT_FOUND: '尚未找到对手。',
  PACK_VERSIONS_REQUIRED: '牌组缺少内容版本信息。',
  PACK_VERSION_MISMATCH: '牌组与当前卡牌内容不兼容。',
  PLAYERS_NOT_LOCKED: '双方锁定行动后才能结算。',
  PLAYER_ALREADY_CONNECTED: '该玩家已经在线。',
  PLAYER_NOT_FOUND: '玩家状态不存在，请重新连接。',
  PRESET_MISSING: '预设牌组不完整。',
  PROTOCOL_MISMATCH: '服务器与客户端版本不兼容，请更新后重试。',
  RANDOM_ONGOING_EFFECT: '持续技能不能随机选择目标。',
  REPEATED_TRIGGER: '技能重复触发次数过多，结算已停止。',
  ROOM_FULL: '房间已满。',
  ROOM_NOT_EMPTY: '当前房间无法开始演武。',
  STAKE_MAXIMUM: '当前战功已经达到上限。',
  TRIGGER_DEPTH_EXCEEDED: '技能连锁层数过多，结算已停止。',
  TURN_LOCKED: '行动已经锁定。',
  TURN_MISMATCH: '回合状态已更新，请重新安排计划。',
  UNKNOWN_ABILITY: '卡牌包含无法识别的技能。',
  UNKNOWN_CARD: '所选卡牌不在当前内容中。',
  UNKNOWN_FRONT: '所选战线不存在。'
};

export const CONNECTION_STATUS_LABELS = {
  idle: '未连接',
  connecting: '连接中',
  connected: '已连接',
  error: '连接失败'
} as const;

export function formatRuleError(code: unknown): string {
  return typeof code === 'string' ? RULE_ERROR_MESSAGES[code] ?? '操作未完成，请稍后重试。' : '操作未完成，请稍后重试。';
}
