<script setup lang="ts">
import { Save } from 'lucide-vue-next';
const { settings, save } = useSettings();
const { locale, setLocale } = useI18n();
</script>
<template>
  <div class="page page-narrow"><header class="page-heading"><div><span class="eyebrow">游戏设置</span><h1>{{ $t('settings.title') }}</h1></div><button class="button primary" type="button" @click="save"><Save :size="17" /> {{ $t('common.save') }}</button></header><section class="settings-section"><h2>界面</h2><label class="field"><span class="field-label">{{ $t('settings.locale') }}</span><select class="select" :value="locale" @change="setLocale(($event.target as HTMLSelectElement).value as 'zh-CN' | 'en')"><option value="zh-CN">简体中文</option><option value="en">English</option></select></label><div class="toggle-row"><div><strong>{{ $t('settings.reducedMotion') }}</strong><p>停用卡牌位移和界面过渡。</p></div><button class="toggle" :class="{ on: settings.reducedMotion }" type="button" role="switch" :aria-checked="settings.reducedMotion" @click="settings.reducedMotion = !settings.reducedMotion; save()" /></div><div class="toggle-row"><div><strong>{{ $t('settings.highContrast') }}</strong><p>提高文字、边框和状态色的对比度。</p></div><button class="toggle" :class="{ on: settings.highContrast }" type="button" role="switch" :aria-checked="settings.highContrast" @click="settings.highContrast = !settings.highContrast; save()" /></div></section><section class="settings-section"><h2>在线</h2><div class="form-grid"><label class="field"><span class="field-label">{{ $t('settings.server') }}</span><input v-model="settings.serverUrl" class="input"></label><label class="field"><span class="field-label">{{ $t('settings.player') }}</span><input v-model="settings.playerName" class="input" maxlength="24"></label></div></section></div>
</template>
<style scoped>.settings-section{margin-top:26px;padding-top:20px;border-top:1px solid var(--line)}.settings-section h2{margin:0 0 16px}.settings-section>.field{max-width:420px}.toggle-row p{margin:4px 0 0;color:var(--muted);font-size:11px}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}@media(max-width:600px){.form-grid{grid-template-columns:1fr}}</style>
